{% set name = "approxposterior" %}
{% set version = "0.4" %}
{% set sha256 = "5a6a64a7291d17450771f2471f92253511e77c86e82b6dcd04d5ffb4a64c1ebc" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - python >=3.5
    - numpy
    - matplotlib
    - scipy
    - george
    - emcee >=3
    - corner
    - scikit-learn
    - h5py

test:
  imports:
    - approxposterior
    - approxposterior.approx

about:
  home: http://github.com/dflemin3/approxposterior
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Python implementation of Bayesian Approximate Posterior Estimation algorithm'

  description: |
    This package is a Python implementation of Bayesian Active Learning for
    Posterior Estimation by Kandasamy et al. (2015) and Adaptive Gaussian
    process approximation for Bayesian inference with expensive likelihood
    functions by Wang & Li (2017). These algorithms allows the user to compute
    approximate posterior probability distributions using computationally
    expensive forward models by training a Gaussian Process (GP) surrogate
    for the likelihood evaluation. The algorithms leverage the inherent
    uncertainty in the GP's predictions to identify high-likelihood regions
    in parameter space where the GP is uncertain. The algorithms then run the
    forward model at these points to compute their likelihood and re-trains
    the GP to maximize the GP's predictive ability while minimizing the number
    of forward model evaluations. Check out Bayesian Active Learning for
    Posterior Estimation by Kandasamy et al. (2015) and Adaptive Gaussian
    process approximation for Bayesian inference with expensive likelihood
    functions by Wang & Li (2017) for in-depth descriptions of the respective
    algorithms.
  doc_url: https://dflemin3.github.io/approxposterior/
  dev_url: https://github.com/dflemin3/approxposterior

extra:
  recipe-maintainers:
    - dflemin3
    - jakevdp
