travis:
  secure:
    BINSTAR_TOKEN: kHnUlKRuo9H3OtV2WEWQ72+pciq1gb7doluEkP2VOPBDfdNRmICCntuGfkYh2Pu+iN7vHjn4AO7mWSLXulf2m08ZMtleQnSLZW5gIc+4llm6HquxuuwNFl0AFBgF29AQG14O8z+9zMxd+a1bY/61LM5ASMnZ1xKGGClMkCxkjcEx3R4t+ifG1MF+JUrnwVXp7sladKYcmYH1VZaWRsPQF+daPUryc39wwqglyW3efiwMWkjy7scNUryR7z/Ku+GmGhPr7iMvQoRfVe7a4Nec1us4Xy0OtJhzJloEiqx5PAGED4cLodnQecQzvZtqvEIEMJRSXkv+T6NMCf/I2dbzp98fpUTEIipAnHBxfSuY/Z2mmmX7gVYfj8BuwlveVvgoi1Dy0FjZG4FTVQYfXqRjEthTh9r2gx0dXl5+BDcaFwBNOPOufs+ti0kWG/dbTVEAzgyU2EHR1UHnstJReqtB8lpbIf2ivD4Mn3O4/g5Q3CwqMFbV9yoA7bZYpl6RjjQuN1ilTTllKrGvR4BD4AFKtU4e5PepTay8R59bn4j8S5z/TUcL/VwvuFp98ihfkcTvhpwpuZoYps+mFYDsBzS8oCFluLV+2WzzDGT7vEYVSJlx6AZ6Nr62ID+eFnNUgoxXIeVBMCdT8ssaX1UAFWY7QyUJsVPJlsr8mdnoBKgx3mU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
