travis:
  secure:
    BINSTAR_TOKEN: fE/o8IhWmuP7yTCG7I3Q6bPdPd15pKWAZclzwFjvLkxk2fjdSuiaK488QgWQgjiuxmymoJaakuvWXXbdKgsUHiCLf2NLJh3/nh/lDdb4aimrNJ3IPaxqNqLZiZOTpItU7PnVzTHY3/OFWBuemgfgZYZEHehKSQ4D+adp8Zbe1INmOFAmcY5MPIrQBC78oe0UdDgR1BQznOR/RKlaOxsBwNxC48IyD0G3oQ1BJNhowa4ADg5okMpIwuO858o86XBFrCs/IHjFBCFJaPnriVtRx7Fp1J0Afa5P933nSmP7fP12/pnqke2WaLWydK+JS8KtVIx4cYDPrLYDfYdSUz/o7kPlVeb/wAUuGUqdWiq3QFmU7J9Cb2is91vD7aM1iun730acE2YmIb5qsHYXrZKECEHH5/gcCjCbjylvSowejvw2JB1OgdtMJWSg8/3joTyKd5N35nt2EiN4bfIWMGnnDKnEji3knV3BpoNxf0OJpUAS89a77nYqueY64oAFCTPThj7s9WQRsv1jnfmO1gZniHaC5M0V3vK+mjBHBH/ubzlwtpIikCFL7cs5z0nxkzOuzkCf60enCPIrjxQ3+f6DoQ5bgsX1la/sTP0hgxoOnsgCOwgxjoyb71/Hd2+nbvaNZB95TUj1s///GKQdR6TPBTpIw5dtQCQ/GPkIMGCXcOk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
